### ISSUE TITLE
Parse error can never be module header or import declaration

### ISSUE THREAD

**Issue by noughtmare** [haskell/error-messages#34]
This code just passed by the Monthly Hask Question thread on Reddit:

```haskell
main :: IO ()
main = putStrLn "Hello World!"

type Addrs = (Char, Int)

copy :: Addrs -> Int
copy (x, y) = y + 1

copy ("Street X", 10)
```

GHC complains:

```
T.hs:9:1: error:
    Parse error: module header, import declaration
    or top-level declaration expected.
  |
9 | copy ("Street X", 10)
  | ^^^^^^^^^^^^^^^^^^^^^
```

But there can never be a module header or import declaration at this point of the program. I would propose changing the message to:

```
T.hs:9:1: error:
    Parse error: top-level declaration expected.
  |
9 | copy ("Street X", 10)
  | ^^^^^^^^^^^^^^^^^^^^^
```

Maybe it could even suggest binding it to a variable?

**Comment by MorrowM** [comment]
Darn, beat me to it haha. #35

**Comment by Ericson2314** [comment]
I think the idea is that this first does parse, because of those dastardly TH implicit top level splices, and then this warning is issued.

If so, I think that *does* in fact mean we have enough info to make this error better: as we comb through the list of "rawer top-level items", we can vary what we suggest based on what we've already seen.

This fits well with the general principle rather than parsing an AST in nearly one pass, very incrementally parse into increasingly less liberal ASTs, starting with a super liberal one, so we get better errors.

**Comment by noughtmare** [comment]
I'll close this one as duplicate of #35 as that seems more elaborate. @Ericson2314 maybe you want to copy your comment to over there?
